baseURL: https://michadenheijer.com/projects/
title: "Projects"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "projects"
